In [2]:
#####include_top=true for 3 fully connected layers. 

In [3]:
from keras.applications.vgg19 import VGG19
from keras.preprocessing import image
from keras.applications.vgg19 import preprocess_input
from keras.models import Model
import numpy as np

base_model = VGG19(weights='imagenet',include_top=True)

Using TensorFlow backend.


In [4]:
base_model.input

<tf.Tensor 'input_1:0' shape=(?, 224, 224, 3) dtype=float32>

In [5]:
model = Model(inputs=base_model.input, outputs=base_model.get_layer('fc2').output)

In [6]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0   

In [7]:
img_path ='C:/Users/aish/OneDrive - Adobe Systems Incorporated/SB/projects/bounded pictures/000330525.png'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

In [8]:
type(x)

numpy.ndarray

In [9]:
print(x)

[[[[ -70.939     -85.779     -63.68    ]
   [ -70.939     -84.779     -65.68    ]
   [ -77.939     -92.779     -70.68    ]
   ...
   [ -85.939    -100.779     -71.68    ]
   [ -83.939     -99.779     -67.68    ]
   [ -70.939     -83.779     -54.68    ]]

  [[ -70.939     -83.779     -60.68    ]
   [ -75.939     -88.779     -65.68    ]
   [ -88.939    -101.779     -78.68    ]
   ...
   [ -83.939     -94.779     -70.68    ]
   [ -93.939    -104.779     -80.68    ]
   [ -82.939     -96.779     -71.68    ]]

  [[ -74.939     -89.779     -67.68    ]
   [ -79.939     -94.779     -72.68    ]
   [ -83.939     -96.779     -73.68    ]
   ...
   [ -64.939     -74.779     -53.68    ]
   [ -66.939     -78.779     -57.68    ]
   [ -54.939003  -69.779     -46.68    ]]

  ...

  [[ -80.939    -111.779     -49.68    ]
   [ -65.939     -95.779     -38.68    ]
   [ -59.939003  -91.779     -29.68    ]
   ...
   [ -49.939003  -63.779     -36.68    ]
   [ -59.939003  -75.779     -43.68    ]
   [ -62.939003 

In [10]:
features = model.predict(x)

In [11]:
print(features.shape)
print(type(features))
print(len(features))

(1, 4096)
<class 'numpy.ndarray'>
1


In [12]:
print(features)

[[0.         0.15364078 0.         ... 0.         0.         0.        ]]


In [13]:
print(features)

[[0.         0.15364078 0.         ... 0.         0.         0.        ]]


In [14]:
import pickle
PIK = "pickle.dat"
my_list=[1,2,3]
with open(PIK, "wb") as f:
    pickle.dump(len(my_list), f)
    for value in my_list:
        pickle.dump(value, f)
data2 = []
with open(PIK, "rb") as f:
    for _ in range(pickle.load(f)):
        data2.append(pickle.load(f))
print (data2)

[1, 2, 3]


In [15]:
import os
type(os.listdir())

list

In [16]:
f=open("C:/Users/aish/OneDrive - Adobe Systems Incorporated/SB/projects/bounded pictures/sum.txt")

In [17]:
f

<_io.TextIOWrapper name='C:/Users/aish/OneDrive - Adobe Systems Incorporated/SB/projects/bounded pictures/sum.txt' mode='r' encoding='cp1252'>

In [18]:
l=f.readlines()

In [19]:
type(l)

list

In [20]:
l = [x.strip().split(' ') for x in l]

In [21]:
l

[['5.74314345e-06', '6.89398121e-06', '8.60930322e-06', '5.30583166e-05'],
 ['7.63499265e-05', '3.49167276e-05', '6.85060804e-04', '1.05555591e-04'],
 ['6.40342068e-06', '2.11105430e-06', '1.53276801e-06', '1.00111254e-06'],
 ['2.37345898e-06', '1.73311605e-06', '1.75348032e-06', '1.64522169e-06'],
 ['6.92932076e-07', '1.88770650e-06', '7.58037913e-06', '7.80109349e-06'],
 ['3.21258540e-06', '6.75542879e-07', '4.69537235e-06', '3.85199701e-06'],
 ['1.48241975e-06', '1.89596685e-05', '4.95795575e-05', '1.37062270e-05'],
 ['2.38539724e-04', '3.32760974e-04', '3.83747902e-05', '3.28766600e-06'],
 ['1.75289839e-04', '2.04688302e-04', '6.87231950e-04', '1.22650803e-04'],
 ['9.06638088e-05', '6.30875584e-05', '2.57301235e-05', '2.91250635e-05'],
 ['9.45838735e-07', '1.19750139e-05', '1.02402037e-05', '9.17628786e-05'],
 ['1.73601002e-05', '3.09539406e-04', '1.45443630e-06', '1.22152069e-05'],
 ['1.66434929e-05', '9.87193707e-05', '1.14952076e-04', '3.44607863e-04'],
 ['7.43425335e-05', '1.32

In [22]:
sm = sum([sum([float(g) for g in x]) for x in l])

In [23]:
sm

1.000000103527353

In [24]:
import os
fileNames=os.listdir()

In [25]:
print(fileNames)

['.ipynb_checkpoints', '000000007.png', '000000037.png', '000000049.png', '000000066.png', '000000069.png', '000000075.png', '000000084.png', '000000110.png', '000000124.png', '000000141.png', '000000165.png', '000000166.png', '000000200.png', '000000201.png', '000000204.png', '000000221.png', '000000223.png', '000000242.png', '000000250.png', '000000256.png', '000000271.png', '000000282.png', '000000284.png', '000000300.png', '000000302.png', '000000313.png', '000000319.png', '000000331.png', '000000337.png', '000000342.png', '000000345.png', '000000351.png', '000000368.png', '000000379.png', '000000381.png', '000000391.png', '000000413.png', '000000433.png', '000000439.png', '000000442.png', '000000450.png', '000000462.png', '000000474.png', '000000486.png', '000000505.png', '000000512.png', '000000517.png', '000000527.png', '000000529.png', '000000537.png', '000000543.png', '000000550.png', '000000551.png', '000000555.png', '000000562.png', '000000582.png', '000000584.png', '0000005

In [26]:
pngfileNames=fileNames[1:-5]
print(pngfileNames)

['000000007.png', '000000037.png', '000000049.png', '000000066.png', '000000069.png', '000000075.png', '000000084.png', '000000110.png', '000000124.png', '000000141.png', '000000165.png', '000000166.png', '000000200.png', '000000201.png', '000000204.png', '000000221.png', '000000223.png', '000000242.png', '000000250.png', '000000256.png', '000000271.png', '000000282.png', '000000284.png', '000000300.png', '000000302.png', '000000313.png', '000000319.png', '000000331.png', '000000337.png', '000000342.png', '000000345.png', '000000351.png', '000000368.png', '000000379.png', '000000381.png', '000000391.png', '000000413.png', '000000433.png', '000000439.png', '000000442.png', '000000450.png', '000000462.png', '000000474.png', '000000486.png', '000000505.png', '000000512.png', '000000517.png', '000000527.png', '000000529.png', '000000537.png', '000000543.png', '000000550.png', '000000551.png', '000000555.png', '000000562.png', '000000582.png', '000000584.png', '000000589.png', '000000592.pn

In [28]:
loc ='C:/Users/aish/OneDrive - Adobe Systems Incorporated/SB/projects/bounded pictures/'
vgg19_dict={}
for image_name in pngfileNames:
    img_path=loc+image_name
    img = image.load_img(img_path, target_size=(224, 224))
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    x = preprocess_input(x)
    features = model.predict(x)
    vgg19_dict[image_name]=features

KeyboardInterrupt: 

In [ ]:
import pickle

example_dict = {1:"6",2:"2",3:"f"}

pickle_out = open("dict.pickle","wb")
pickle.dump(example_dict, pickle_out)
pickle_out.close()

pickle_in = open("dict.pickle","rb")
example_dict = pickle.load(pickle_in)
print(example_dict)

In [ ]:
[(vgg_a , vgg_b) , (vgg_c , vgg_d) , (vgg_p , vgg_q) , ....(vgg_x , vgg_y)]=tr_x
[1,0,1,....1] = tr_y


In [36]:
tr_pairs=np.array([(features,features),(features,features)])
tr_y=np.array([(1,1),(1,1)])
te_pairs=np.array([(features,features),(features,features)])
te_y=np.array([(1,1),(1,1)])

In [37]:
print(tr_pairs)

[[[[0.4318961 1.8048298 0.        ... 0.        0.        1.6048787]]

  [[0.4318961 1.8048298 0.        ... 0.        0.        1.6048787]]]


 [[[0.4318961 1.8048298 0.        ... 0.        0.        1.6048787]]

  [[0.4318961 1.8048298 0.        ... 0.        0.        1.6048787]]]]


In [42]:
from __future__ import absolute_import
from __future__ import print_function
import numpy as np

import random
from keras.datasets import mnist
from keras.models import Model
from keras.layers import Input, Flatten, Dense, Dropout, Lambda
from keras.optimizers import RMSprop
from keras import backend as K

num_classes = 10
epochs = 2

In [39]:



def euclidean_distance(vects):
    x, y = vects
    sum_square = K.sum(K.square(x - y), axis=1, keepdims=True)
    return K.sqrt(K.maximum(sum_square, K.epsilon()))


def eucl_dist_output_shape(shapes):
    shape1, shape2 = shapes
    return (shape1[0], 1)


def contrastive_loss(y_true, y_pred):
    '''Contrastive loss from Hadsell-et-al.'06
    http://yann.lecun.com/exdb/publis/pdf/hadsell-chopra-lecun-06.pdf
    '''
    margin = 1
    square_pred = K.square(y_pred)
    margin_square = K.square(K.maximum(margin - y_pred, 0))
    return K.mean(y_true * square_pred + (1 - y_true) * margin_square)


def create_pairs(x, digit_indices):
    '''Positive and negative pair creation.
    Alternates between positive and negative pairs.
    '''
    pairs = []
    labels = []
    n = min([len(digit_indices[d]) for d in range(num_classes)]) - 1
    for d in range(num_classes):
        for i in range(n):
            z1, z2 = digit_indices[d][i], digit_indices[d][i + 1]
            pairs += [[x[z1], x[z2]]]
            inc = random.randrange(1, num_classes)
            dn = (d + inc) % num_classes
            z1, z2 = digit_indices[d][i], digit_indices[dn][i]
            pairs += [[x[z1], x[z2]]]
            labels += [1, 0]
    return np.array(pairs), np.array(labels)


def create_base_network(input_shape): #vgg19 vector input
    '''Base network to be shared (eq. to feature extraction).
    '''
    input = Input(shape=input_shape)
    x = Flatten()(input) #leaving flattening
    x = Dense(128, activation='relu')(x)
    x = Dropout(0.1)(x)
    x = Dense(128, activation='relu')(x)
    x = Dropout(0.1)(x)
    x = Dense(128, activation='relu')(x)
    return Model(input, x)


def compute_accuracy(y_true, y_pred):
    '''Compute classification accuracy with a fixed threshold on distances.
    '''
    pred = y_pred.ravel() < 0.5
    return np.mean(pred == y_true)


def accuracy(y_true, y_pred):
    '''Compute classification accuracy with a fixed threshold on distances.
    '''
    return K.mean(K.equal(y_true, K.cast(y_pred < 0.5, y_true.dtype)))




In [43]:
# the data, split between train and test sets
#no normalization needed.


input_shape = (1,4096)



print(tr_pairs)
print(tr_y)
print(te_pairs)
print(te_y)


# network definition
base_network = create_base_network(input_shape)

input_a = Input(shape=input_shape) #same as shape of vgg vector
input_b = Input(shape=input_shape)

# because we re-use the same instance `base_network`,
# the weights of the network
# will be shared across the two branches
processed_a = base_network(input_a) # defining the computation
processed_b = base_network(input_b)

distance = Lambda(euclidean_distance,
                  output_shape=eucl_dist_output_shape)([processed_a, processed_b])

model = Model([input_a, input_b], distance)

# train
rms = RMSprop()
model.compile(loss=contrastive_loss, optimizer=rms, metrics=[accuracy])

#vgg vectors for img1 , img2 and label=s,dissimalar.
#skippin validation
#training the model here.
model.fit([tr_pairs[:, 0], tr_pairs[:, 1]], tr_y,
          batch_size=128,
          epochs=epochs,
          validation_data=([te_pairs[:, 0], te_pairs[:, 1]], te_y))

#pass my vgg vectors to base_network. processed_a wd have final img embedding. Any new img seacrh for similiarity 
#getting new vgg vector, passing thru n/w to get embeddings and then do a KNN search.


#not interested in prediciting
# compute final accuracy on training and test sets
y_pred = model.predict([tr_pairs[:, 0], tr_pairs[:, 1]])
tr_acc = compute_accuracy(tr_y, y_pred)
y_pred = model.predict([te_pairs[:, 0], te_pairs[:, 1]])
te_acc = compute_accuracy(te_y, y_pred)

print('* Accuracy on training set: %0.2f%%' % (100 * tr_acc))
print('* Accuracy on test set: %0.2f%%' % (100 * te_acc))

[[[[0.4318961 1.8048298 0.        ... 0.        0.        1.6048787]]

  [[0.4318961 1.8048298 0.        ... 0.        0.        1.6048787]]]


 [[[0.4318961 1.8048298 0.        ... 0.        0.        1.6048787]]

  [[0.4318961 1.8048298 0.        ... 0.        0.        1.6048787]]]]
[[1 1]
 [1 1]]
[[[[0.4318961 1.8048298 0.        ... 0.        0.        1.6048787]]

  [[0.4318961 1.8048298 0.        ... 0.        0.        1.6048787]]]


 [[[0.4318961 1.8048298 0.        ... 0.        0.        1.6048787]]

  [[0.4318961 1.8048298 0.        ... 0.        0.        1.6048787]]]]
[[1 1]
 [1 1]]
Train on 2 samples, validate on 2 samples
Epoch 1/2
2/2 [==============================] - 1s 373ms/step - loss: 13.9176 - accuracy: 0.0000e+00 - val_loss: 1.0000e-07 - val_accuracy: 1.0000
Epoch 2/2
2/2 [==============================] - 0s 10ms/step - loss: 86.7728 - accuracy: 0.0000e+00 - val_loss: 1.0000e-07 - val_accuracy: 1.0000
* Accuracy on training set: 100.00%
* Accuracy on test set:

In [46]:
print(processed_a,processed_a)

Tensor("model_4/dense_6/Relu:0", shape=(?, 128), dtype=float32) Tensor("model_4/dense_6/Relu:0", shape=(?, 128), dtype=float32)


In [47]:
vgg19_dict

{'000000007.png': array([[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
         3.2664099]], dtype=float32),
 '000000037.png': array([[0.      , 0.      , 0.      , ..., 0.      , 0.      , 3.577426]],
       dtype=float32),
 '000000049.png': array([[0.        , 0.        , 0.        , ..., 0.        , 0.44682333,
         3.3983512 ]], dtype=float32),
 '000000066.png': array([[0.        , 0.        , 0.        , ..., 0.00760841, 0.        ,
         0.        ]], dtype=float32),
 '000000069.png': array([[0.       , 0.       , 0.       , ..., 0.       , 3.1178553,
         1.2575047]], dtype=float32),
 '000000075.png': array([[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
         1.4897063]], dtype=float32),
 '000000084.png': array([[0.       , 0.       , 0.       , ..., 0.       , 0.4552459,
         0.2919999]], dtype=float32),
 '000000110.png': array([[0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 '000000124.png': array([[0.       , 0.       , 0.     